#!/usr/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

cd ../projects/app
if [ -f .env ]; then
    rm .env
    cp ~/env .env
fi
echo Startig in background...
sudo pnpm start -H 0.0.0.0 -p 80 > sys.log 2>&1 &
disown -h %1
tail -f sys.log
